// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quantum.Data;

#nullable disable

namespace Quantum.Migrations.MySqlMigrations
{
    [DbContext(typeof(QuantumMySqlDbContext))]
    [Migration("20260923074047_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Quantum.Entities.Model.AiConversationModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("AllowEnvValues")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastMessageTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("t_ai_conversation");
                });

            modelBuilder.Entity("Quantum.Entities.Model.AiMessageModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<string>("ConversationId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Kind")
                        .HasColumnType("longtext");

                    b.Property<string>("Payload")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.Property<string>("RunId")
                        .HasColumnType("longtext");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "Seq");

                    b.ToTable("t_ai_message");
                });

            modelBuilder.Entity("Quantum.Entities.Model.AiModelModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ContextWindow")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext");

                    b.Property<bool>("Enable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxOutputTokens")
                        .HasColumnType("int");

                    b.Property<string>("ModelId")
                        .HasColumnType("longtext");

                    b.Property<string>("ProviderId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<double>("Temperature")
                        .HasColumnType("double");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("t_ai_model");
                });

            modelBuilder.Entity("Quantum.Entities.Model.AiProposalModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("AppliedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AppliedVersionId")
                        .HasColumnType("longtext");

                    b.Property<string>("BaseHash")
                        .HasColumnType("longtext");

                    b.Property<string>("ConversationId")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Diagnostics")
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext");

                    b.Property<string>("MessageId")
                        .HasColumnType("longtext");

                    b.Property<string>("NewContent")
                        .HasColumnType("longtext");

                    b.Property<string>("NewHash")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext");

                    b.Property<string>("TestRunLogId")
                        .HasColumnType("longtext");

                    b.Property<string>("TestStatus")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("t_ai_proposal");
                });

            modelBuilder.Entity("Quantum.Entities.Model.AiProviderModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ApiKey")
                        .HasColumnType("longtext");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Enable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastTestMessage")
                        .HasColumnType("longtext");

                    b.Property<bool?>("LastTestOk")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastTestTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Protocol")
                        .HasColumnType("longtext");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<int>("SupportsTools")
                        .HasColumnType("int");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("UsePlatformProxy")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("t_ai_provider");
                });

            modelBuilder.Entity("Quantum.Entities.Model.AiRunModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("int");

                    b.Property<string>("ConversationId")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Error")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FinishTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("int");

                    b.Property<string>("ProviderId")
                        .HasColumnType("longtext");

                    b.Property<int>("Rounds")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("TargetFile")
                        .HasColumnType("longtext");

                    b.Property<string>("TriggerType")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("t_ai_run");
                });

            modelBuilder.Entity("Quantum.Entities.Model.AiSettingModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("AllowCustomDataManage")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowEnvManage")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowScriptDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowTaskManage")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AutoAnalyzeOnFailure")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Enable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("KeepVersionsPerFile")
                        .HasColumnType("int");

                    b.Property<int>("LogTailLines")
                        .HasColumnType("int");

                    b.Property<int>("MaxRounds")
                        .HasColumnType("int");

                    b.Property<int>("RunTimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("SaveFullPrompt")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SystemPromptExtra")
                        .HasColumnType("longtext");

                    b.Property<string>("TestRunNotifyMode")
                        .HasColumnType("longtext");

                    b.Property<bool>("TestRunRequireConfirm")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("t_ai_setting");
                });

            modelBuilder.Entity("Quantum.Entities.Model.AiStepModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Arguments")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Kind")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Result")
                        .HasColumnType("longtext");

                    b.Property<string>("RunId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Seq")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Seq");

                    b.ToTable("t_ai_step");
                });

            modelBuilder.Entity("Quantum.Entities.Model.AppDeviceModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceId")
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceName")
                        .HasColumnType("longtext");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Platform")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("t_app_device");
                });

            modelBuilder.Entity("Quantum.Entities.Model.AppFileModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ContentType")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Ext")
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreateTime");

                    b.ToTable("t_app_file");
                });

            modelBuilder.Entity("Quantum.Entities.Model.AppNotificationModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Jump")
                        .HasColumnType("longtext");

                    b.Property<string>("MsgId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("t_app_notification");
                });

            modelBuilder.Entity("Quantum.Entities.Model.AppNotifySettingModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DndEnd")
                        .HasColumnType("longtext");

                    b.Property<string>("DndStart")
                        .HasColumnType("longtext");

                    b.Property<bool>("SecurityPush")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SystemPush")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TaskPush")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("t_app_notify_setting");
                });

            modelBuilder.Entity("Quantum.Entities.Model.AppRefreshTokenModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceId")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Revoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("longtext");

                    b.Property<string>("TokenHash")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("t_app_refresh_token");
                });

            modelBuilder.Entity("Quantum.Entities.Model.Bookmark", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ParentId")
                        .HasColumnType("longtext");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("t_bookmark");
                });

            modelBuilder.Entity("Quantum.Entities.Model.ChatMessageModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<string>("ContentText")
                        .HasColumnType("longtext");

                    b.Property<string>("ContentType")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<string>("MsgId")
                        .HasColumnType("longtext");

                    b.Property<string>("Payload")
                        .HasColumnType("longtext");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint");

                    b.Property<string>("SessionKey")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Seq")
                        .IsUnique();

                    b.HasIndex("SessionKey", "Seq");

                    b.ToTable("t_chat_message");
                });

            modelBuilder.Entity("Quantum.Entities.Model.ChatSessionModel", b =>
                {
                    b.Property<string>("SessionKey")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("LastReadSeq")
                        .HasColumnType("bigint");

                    b.Property<long>("LastSeq")
                        .HasColumnType("bigint");

                    b.HasKey("SessionKey");

                    b.ToTable("t_chat_session");
                });

            modelBuilder.Entity("Quantum.Entities.Model.CommandModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("CommunicationType")
                        .HasColumnType("int");

                    b.Property<bool>("Enable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableRegex")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Key")
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<int>("MessageType")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("t_command");
                });

            modelBuilder.Entity("Quantum.Entities.Model.CustomDataModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Data1")
                        .HasColumnType("longtext");

                    b.Property<string>("Data10")
                        .HasColumnType("longtext");

                    b.Property<string>("Data11")
                        .HasColumnType("longtext");

                    b.Property<string>("Data12")
                        .HasColumnType("longtext");

                    b.Property<string>("Data13")
                        .HasColumnType("longtext");

                    b.Property<string>("Data14")
                        .HasColumnType("longtext");

                    b.Property<string>("Data15")
                        .HasColumnType("longtext");

                    b.Property<string>("Data2")
                        .HasColumnType("longtext");

                    b.Property<string>("Data3")
                        .HasColumnType("longtext");

                    b.Property<string>("Data4")
                        .HasColumnType("longtext");

                    b.Property<string>("Data5")
                        .HasColumnType("longtext");

                    b.Property<string>("Data6")
                        .HasColumnType("longtext");

                    b.Property<string>("Data7")
                        .HasColumnType("longtext");

                    b.Property<string>("Data8")
                        .HasColumnType("longtext");

                    b.Property<string>("Data9")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.ToTable("t_custom_data");
                });

            modelBuilder.Entity("Quantum.Entities.Model.CustomDataTitleModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Hide")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title1")
                        .HasColumnType("longtext");

                    b.Property<string>("Title10")
                        .HasColumnType("longtext");

                    b.Property<string>("Title11")
                        .HasColumnType("longtext");

                    b.Property<string>("Title12")
                        .HasColumnType("longtext");

                    b.Property<string>("Title13")
                        .HasColumnType("longtext");

                    b.Property<string>("Title14")
                        .HasColumnType("longtext");

                    b.Property<string>("Title15")
                        .HasColumnType("longtext");

                    b.Property<string>("Title2")
                        .HasColumnType("longtext");

                    b.Property<string>("Title3")
                        .HasColumnType("longtext");

                    b.Property<string>("Title4")
                        .HasColumnType("longtext");

                    b.Property<string>("Title5")
                        .HasColumnType("longtext");

                    b.Property<string>("Title6")
                        .HasColumnType("longtext");

                    b.Property<string>("Title7")
                        .HasColumnType("longtext");

                    b.Property<string>("Title8")
                        .HasColumnType("longtext");

                    b.Property<string>("Title9")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<string>("TypeName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("t_custom_data_title");
                });

            modelBuilder.Entity("Quantum.Entities.Model.EnvModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Enable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("t_env");
                });

            modelBuilder.Entity("Quantum.Entities.Model.LogModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DirectoryName")
                        .HasColumnType("longtext");

                    b.Property<long?>("ElapsedMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Exception")
                        .HasColumnType("longtext");

                    b.Property<string>("LogPath")
                        .HasColumnType("longtext");

                    b.Property<int>("LogType")
                        .HasColumnType("int");

                    b.Property<string>("Module")
                        .HasColumnType("longtext");

                    b.Property<string>("Operator")
                        .HasColumnType("longtext");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<string>("RequestPath")
                        .HasColumnType("longtext");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<string>("UserIP")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CreateTime");

                    b.ToTable("t_log");
                });

            modelBuilder.Entity("Quantum.Entities.Model.MenuModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Component")
                        .HasColumnType("longtext");

                    b.Property<bool>("HideInBread")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HideInMenu")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("ParentName")
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("t_menu");
                });

            modelBuilder.Entity("Quantum.Entities.Model.OpenTriggerTask", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("Enable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableProxy")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnablePush")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Envs")
                        .HasColumnType("longtext");

                    b.Property<string>("HttpMethod")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SrciptFile")
                        .HasColumnType("longtext");

                    b.Property<string>("Whitelist")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Secret");

                    b.ToTable("t_opentriggertask");
                });

            modelBuilder.Entity("Quantum.Entities.Model.ScriptVersionModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Hash")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LineCount")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasColumnType("longtext");

                    b.Property<string>("TaskId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FileName", "CreateTime");

                    b.ToTable("t_script_version");
                });

            modelBuilder.Entity("Quantum.Entities.Model.TaskModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Command")
                        .HasColumnType("longtext");

                    b.Property<string>("CommandEnv")
                        .HasColumnType("longtext");

                    b.Property<string>("CommunicationTypes")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Cron")
                        .HasColumnType("longtext");

                    b.Property<int>("DayLimit")
                        .HasColumnType("int");

                    b.Property<bool>("Enable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableProxy")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnablePush")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EnableRegex")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext");

                    b.Property<bool>("Manager")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<bool>("PushGroup")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<bool>("Revocation")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SessionName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TaskEndNotify")
                        .HasColumnType("longtext");

                    b.Property<string>("TaskStartNotify")
                        .HasColumnType("longtext");

                    b.Property<int>("TaskStatus")
                        .HasColumnType("int");

                    b.Property<string>("TaskThreadId")
                        .HasColumnType("longtext");

                    b.Property<bool>("TextToPicture")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("WaitTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("t_task");
                });

            modelBuilder.Entity("Quantum.Entities.Model.TaskSubModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Command")
                        .HasColumnType("longtext");

                    b.Property<string>("CommandEnv")
                        .HasColumnType("longtext");

                    b.Property<bool>("EnableRegex")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext");

                    b.Property<bool>("Revocation")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<string>("TaskId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("WaitTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("t_task_sub");
                });
#pragma warning restore 612, 618
        }
    }
}
